name: Airtable Sessions Deduplication Sync

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    outputs:
      last_sync_time: ${{ steps.sync.outputs.last_sync_time }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyairtable

      - name: Restore sync state cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: last_sync_state.txt
          key: airtable-sync-state
          restore-keys: airtable-sync-
        continue-on-error: true

      - name: Run Airtable sync script
        id: sync
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_SOURCE_TABLE: ${{ secrets.AIRTABLE_SOURCE_TABLE }}
          AIRTABLE_DEST_TABLE: ${{ secrets.AIRTABLE_DEST_TABLE }}
          AIRTABLE_VIEW_NAME: ${{ secrets.AIRTABLE_VIEW_NAME }}
        run: python sessions_dedup_sync.py

      - name: Save sync state cache
        uses: actions/cache/save@v4
        with:
          path: last_sync_state.txt
          # Use a unique key for each run by appending timestamp
          key: airtable-sync-${{ steps.timestamp.outputs.time }}