name: Airtable Sessions Deduplication Sync

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    outputs:
      last_sync_time: ${{ steps.sync.outputs.last_sync_time }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyairtable

      - name: Get last sync time
        id: get_time
        run: echo "LAST_SYNC_TIME=$(cat .github/sync_state || echo '')" >> $GITHUB_ENV

      - name: Run Airtable sync script
        id: sync
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_SOURCE_TABLE: ${{ secrets.AIRTABLE_SOURCE_TABLE }}
          AIRTABLE_DEST_TABLE: ${{ secrets.AIRTABLE_DEST_TABLE }}
          AIRTABLE_VIEW_NAME: ${{ secrets.AIRTABLE_VIEW_NAME }}
        run: python sync_airtable.py

      - name: Save last sync time
        if: steps.sync.outputs.last_sync_time != ''
        run: echo "${{ steps.sync.outputs.last_sync_time }}" > .github/sync_state